-- AddBankTaxFields
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "panNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ufn" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankAccountNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ifscCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "taxRegime" TEXT DEFAULT 'NEW';
